Add loop to attempt to fetch gpg 3 times

diff --git a/src/commands/install.yml b/src/commands/install.yml
--- a/src/commands/install.yml
+++ b/src/commands/install.yml
@@ -12,12 +12,23 @@ steps:
         if [[ $EUID -ne 0 ]]; then
           SUDO=sudo
         fi
-        gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
+        count=0
+        until gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
+        do
+            count=$((count+1)); sleep 5;
+            if [ $count -gt 2 ]; then
+                echo "Unable to receive GPG keys, FAILING";
+                exit 1; 
+            fi; 
+          echo "Network error: Unable to receive GPG keys. Will attempt again ($count/3)";
+        done; 
+        
+        
+        ## Update if RVM is installed and exit
         if [ -x "$(command -v rvm -v)" ]; then
           rvm get stable
           exit 0
         fi
-        # Fix for retrieving GPG over IPv6 issue
 
         curl -sSL "https://get.rvm.io" | bash -s stable
         $SUDO adduser $(whoami) rvm
